import type { StudentProfile } from "@/types/profile";

export const SAMPLE_PROFILES: StudentProfile[] = [
  {
    id: "p1",
    userId: "u1",
    fullName: "Aisha Bello",
    avatarUrl: undefined,
    school: "University of Abuja",
    courseOfStudy: "Information Science",
    bio: "Designer who loves turning student pain points into beautiful interfaces.",
    skillLevel: "intermediate",
    skills: ["UI/UX Design", "Research", "Pitching"],
    interests: ["Education", "Productivity", "Social Impact"],
    goals: ["Join a hackathon team", "Build portfolio projects"],
    collaborationTypes: ["hackathon-team", "project-collaboration"],
    availability: [
      { day: "saturday", period: "evening" },
      { day: "sunday", period: "afternoon" },
    ],
    communicationPreference: "chat",
    portfolioUrl: "https://aisha.design",
    githubUrl: "https://github.com/aisha",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "p2",
    userId: "u2",
    fullName: "David Okafor",
    school: "Baze University",
    courseOfStudy: "Computer Science",
    bio: "Backend engineer obsessed with clean APIs and scalable architecture.",
    skillLevel: "advanced",
    skills: ["Backend Development", "Database Design", "API Integration"],
    interests: ["FinTech", "AI Tools", "Productivity"],
    goals: ["Build scalable apps", "Mentor beginners"],
    collaborationTypes: ["mentor", "hackathon-team"],
    availability: [
      { day: "friday", period: "evening" },
      { day: "saturday", period: "morning" },
    ],
    communicationPreference: "video",
    githubUrl: "https://github.com/davidok",
    linkedinUrl: "https://linkedin.com/in/davidok",
    createdAt: "2026-04-02T10:00:00Z",
    updatedAt: "2026-04-02T10:00:00Z",
  },
  {
    id: "p3",
    userId: "u3",
    fullName: "Zainab Musa",
    school: "Nile University",
    courseOfStudy: "Software Engineering",
    bio: "First-time hackathon participant excited to learn and build.",
    skillLevel: "beginner",
    skills: ["Frontend Development", "Content Writing"],
    interests: ["Education", "Scholarships", "Community"],
    goals: ["Find a project team", "Improve coding skills"],
    collaborationTypes: ["hackathon-team", "mentee", "study-partner"],
    availability: [
      { day: "friday", period: "evening" },
      { day: "saturday", period: "afternoon" },
    ],
    communicationPreference: "chat",
    githubUrl: "https://github.com/zainabm",
    createdAt: "2026-04-03T10:00:00Z",
    updatedAt: "2026-04-03T10:00:00Z",
  },
  {
    id: "p4",
    userId: "u4",
    fullName: "Emeka Nwosu",
    school: "Veritas University",
    courseOfStudy: "Computer Engineering",
    bio: "Mobile dev building tools that actually help students.",
    skillLevel: "intermediate",
    skills: ["Mobile Development", "Firebase", "Pitching"],
    interests: ["HealthTech", "Student Life", "AI Tools"],
    goals: ["Build a hackathon MVP", "Find a designer"],
    collaborationTypes: ["hackathon-team", "project-collaboration"],
    availability: [
      { day: "saturday", period: "morning" },
      { day: "sunday", period: "afternoon" },
    ],
    communicationPreference: "flexible",
    portfolioUrl: "https://emeka.dev",
    createdAt: "2026-04-04T10:00:00Z",
    updatedAt: "2026-04-04T10:00:00Z",
  },
  {
    id: "p5",
    userId: "u5",
    fullName: "Chiamaka Eze",
    school: "Covenant University",
    courseOfStudy: "Data Science",
    bio: "ML enthusiast turning datasets into useful student tools.",
    skillLevel: "advanced",
    skills: ["AI/ML", "Data Analysis", "Backend Development"],
    interests: ["AI Tools", "Education", "Productivity"],
    goals: ["Ship an AI project", "Find UX collaborator"],
    collaborationTypes: ["project-collaboration", "mentor"],
    availability: [
      { day: "wednesday", period: "evening" },
      { day: "saturday", period: "afternoon" },
    ],
    communicationPreference: "video",
    githubUrl: "https://github.com/chiamaka",
    createdAt: "2026-04-05T10:00:00Z",
    updatedAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "p6",
    userId: "u6",
    fullName: "Tunde Adewale",
    school: "University of Lagos",
    courseOfStudy: "Business Administration",
    bio: "Product-minded builder who loves pitching student startups.",
    skillLevel: "intermediate",
    skills: ["Product Management", "Pitching", "Marketing"],
    interests: ["FinTech", "Creator Economy", "Social Impact"],
    goals: ["Launch a startup", "Find technical co-founder"],
    collaborationTypes: ["project-collaboration", "hackathon-team"],
    availability: [
      { day: "thursday", period: "evening" },
      { day: "sunday", period: "morning" },
    ],
    communicationPreference: "in-person",
    linkedinUrl: "https://linkedin.com/in/tundea",
    createdAt: "2026-04-06T10:00:00Z",
    updatedAt: "2026-04-06T10:00:00Z",
  },
];
